### ISSUE TITLE
Fix demo link on Github

### ISSUE THREAD

**Issue by RoneoOrg** [omar-faruk02/Lifistyle-blog#1]
Hi there,

the demo link in the sidebar on Github is pointing to Vercel instead of Netlify

BTW, this is how the demo looks like, is it on purpose? (The title fonts seem randomly rendered -- tested on FF and Chromium)

![Capture d’écran de 2022-01-11 23-53-28](https://user-images.githubusercontent.com/77257518/149034321-83ef73ac-6690-4f91-b4a0-4d2cc0accbc4.png)

**Comment by tfsomrat** [comment]
Hello @RoneoOrg 

Thank you for your concern, This was a wrong commit, we are working on it. We are gonna fix it ASAP.

EDIT: issue resolved
